package com.brucefox.model;
// default package
// Generated Jan 22, 2018 10:36:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", catalog = "task_db")
public class Task implements java.io.Serializable {


	private Long id;
	private Integer quoteNumber;
	private String quoteName;
	private String contact;
	private String task;
	private String tasktype;
	private Date duedate;

	public Task() {
	}

	public Task(Integer quoteNumber, String quoteName, String contact, String task, String tasktype, Date duedate) {
		this.quoteNumber = quoteNumber;
		this.quoteName = quoteName;
		this.contact = contact;
		this.task = task;
		this.tasktype = tasktype;
		this.duedate = duedate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "quote_number")
	public Integer getQuoteNumber() {
		return this.quoteNumber;
	}

	public void setQuoteNumber(Integer quoteNumber) {
		this.quoteNumber = quoteNumber;
	}

	@Column(name = "quote_name", length = 45)
	public String getQuoteName() {
		return this.quoteName;
	}

	public void setQuoteName(String quoteName) {
		this.quoteName = quoteName;
	}

	@Column(name = "contact", length = 45)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "task", length = 500)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "tasktype", length = 45)
	public String getTasktype() {
		return this.tasktype;
	}

	public void setTasktype(String tasktype) {
		this.tasktype = tasktype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "duedate", length = 19)
	public Date getDuedate() {
		return this.duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}
	

	@Override
	public String toString() {
		return "Task [id=" + id + ", quoteNumber=" + quoteNumber + ", quoteName=" + quoteName + ", contact=" + contact
				+ ", task=" + task + ", tasktype=" + tasktype + ", duedate=" + duedate + "]";
	}

}
